<a href="https://colab.research.google.com/github/phaneena/Learn.py-/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
array= np.random.randint(10,size=(3,3))
print(array)

[[1 0 3]
 [5 2 6]
 [9 9 6]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
import numpy as np
array1= np.random.randint(10,size=(4,4))
print(array1)
array2=np.random.randint(10,size=(4,4))
print(array2)
x=array1.reshape(2,8)
y=array2.reshape(2,8)
print (np.hstack((x,y)))
print (np.vstack((x,y)))

[[0 3 6 0]
 [7 8 4 8]
 [9 7 3 3]
 [3 1 3 1]]
[[1 2 7 4]
 [9 8 9 2]
 [5 2 5 7]
 [7 7 8 0]]
[[0 3 6 0 7 8 4 8 1 2 7 4 9 8 9 2]
 [9 7 3 3 3 1 3 1 5 2 5 7 7 7 8 0]]
[[0 3 6 0 7 8 4 8]
 [9 7 3 3 3 1 3 1]
 [1 2 7 4 9 8 9 2]
 [5 2 5 7 7 7 8 0]]
